IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'File')
BEGIN
	CREATE TABLE [dbo].[File] (
		[FileId] INT NOT NULL IDENTITY(1,1),
		[Name] NVARCHAR(200) NOT NULL,
		[Extension] NVARCHAR(10) NOT NULL,
		[Content] VARBINARY(MAX) NOT NULL,
		[NavId] INT NOT NULL,
		[CreatedOn] DATETIME CONSTRAINT DF_File_CreatedOn DEFAULT GETDATE() NOT NULL,
		CONSTRAINT PK_FileId PRIMARY KEY ([FileId]),
		CONSTRAINT FK_FileNavId_Nav FOREIGN KEY ([NavId]) REFERENCES [dbo].[Nav] ([NavId]) ON DELETE CASCADE ON UPDATE NO ACTION
	);
END
GO