IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Link')
BEGIN
	CREATE TABLE [dbo].[Link] (
		[LinkId] INT NOT NULL IDENTITY(1,1),
		[Url] NVARCHAR(500) NOT NULL,
		[Title] NVARCHAR(100) NOT NULL,
		[OpenNewTab] BIT CONSTRAINT DF_Link_OpenNewTab DEFAULT 0 NOT NULL,
		[NavId] INT NOT NULL,
		[CreatedOn] DATETIME CONSTRAINT DF_Link_CreatedOn DEFAULT GETDATE() NOT NULL,
		CONSTRAINT PK_LinkId PRIMARY KEY ([LinkId]),
		CONSTRAINT FK_LinkNavId_Nav FOREIGN KEY ([NavId]) REFERENCES [dbo].[Nav] ([NavId]) ON DELETE CASCADE ON UPDATE NO ACTION
	);
END
GO