IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Nav')
BEGIN
	CREATE TABLE [dbo].[Nav] (
		[NavId] INT NOT NULL IDENTITY(1,1),
		[Name] NVARCHAR(50) NOT NULL,
		[Url] NVARCHAR(500) NULL,
		[ParentNavId] INT NULL,
		[CreatedOn] DATETIME CONSTRAINT DF_Nav_CreatedOn DEFAULT GETDATE() NOT NULL,
		CONSTRAINT PK_NavId PRIMARY KEY ([NavId]),
		CONSTRAINT FK_ParentNavId_NavId FOREIGN KEY ([ParentNavId]) REFERENCES [dbo].[Nav] ([NavId]) ON DELETE NO ACTION
	);
END
GO